spring:
  redis:
    database: 7
    host: ${REDIS_HOST:106.14.95.202}
    port: ${REDIS_PORT:9582}
    timeout: 1s
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: 1s
        min-idle: 10
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/micolor?useUnicode=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF8
    username: root
    password: 1qaz@wsx